services:
  goal-tracker-backend-service:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env.dev
  goal-tracker-frontend-service:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev.vite
    ports:
      - "8080:8080"
  goal-tracker-nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev.nginx
    ports:
      - "80:80"
