apiVersion: v1
kind: Service
metadata:
  name: goal-tracker-frontend-service
spec:
  selector:
    app: goal-tracker-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
  loadBalancerClass: tailscale