"""add required_activities_per_period to goal

Revision ID: 07ed0f5eea5f
Revises:
Create Date: 2025-04-10 11:11:51.423597

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "07ed0f5eea5f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "goal", sa.Column("required_activites_per_period", sa.Integer(), nullable=False, default=1, server_default="1")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("goal", "required_activites_per_period")
    # ### end Alembic commands ###
