"""fix column name

Revision ID: f5205fea0dcb
Revises: 07ed0f5eea5f
Create Date: 2025-04-10 12:11:36.021891

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f5205fea0dcb"
down_revision: Union[str, None] = "07ed0f5eea5f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "goal", sa.Column("required_activities_per_period", sa.Integer(), nullable=False, server_default=sa.text("1"))
    )
    op.drop_column("goal", "required_activites_per_period")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "goal",
        sa.Column(
            "required_activites_per_period",
            sa.INTEGER(),
            server_default=sa.text("1"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("goal", "required_activities_per_period")
    # ### end Alembic commands ###
