"""Split activity completion field

Revision ID: c4cdfe5dd170
Revises: 3cced2940039
Create Date: 2025-04-16 12:21:17.055732

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c4cdfe5dd170"
down_revision: Union[str, None] = "3cced2940039"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM activity")
    op.add_column("activity", sa.Column("completed_year", sa.Integer(), nullable=False))
    op.add_column("activity", sa.Column("completed_month", sa.Integer(), nullable=False))
    op.add_column("activity", sa.Column("completed_day", sa.Integer(), nullable=False))
    op.drop_column("activity", "completed")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("activity", sa.Column("completed", postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column("activity", "completed_day")
    op.drop_column("activity", "completed_month")
    op.drop_column("activity", "completed_year")
    # ### end Alembic commands ###
