"""Add count to activity

Revision ID: 371d9b415c77
Revises: f5205fea0dcb
Create Date: 2025-04-14 11:52:23.866330

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "371d9b415c77"
down_revision: Union[str, None] = "f5205fea0dcb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("activity", sa.Column("count", sa.Integer(), nullable=False, default=1, server_default="1"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("activity", "count")
    # ### end Alembic commands ###
