"""Migrating account table

Revision ID: 4983effd1751
Revises: c4cdfe5dd170
Create Date: 2025-04-18 09:24:45.850351

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4983effd1751"
down_revision: Union[str, None] = "c4cdfe5dd170"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_account", sa.Column("email", sa.String(), nullable=True))
    op.execute("UPDATE user_account SET email = 'andrew.mckit@gmail.com' WHERE name = 'amckit'")
    op.execute("UPDATE user_account SET email = 'lindsmaykc@gmail.com' WHERE name = 'lmckit'")
    op.alter_column("user_account", "email", nullable=False)

    op.alter_column("user_account", "fullname", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_constraint("user_account_name_key", "user_account", type_="unique")
    op.create_unique_constraint("user_account_unique_email", "user_account", ["email"])
    op.drop_column("user_account", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_account", sa.Column("name", sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.drop_constraint("user_account_unique_email", "user_account", type_="unique")
    op.create_unique_constraint("user_account_name_key", "user_account", ["name"])
    op.alter_column("user_account", "fullname", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("user_account", "email")
    # ### end Alembic commands ###
